services:
  front_supply_db:
    container_name: front_supply_db
    hostname: front_supply_db
    image: postgres:16.9-bookworm
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432