services:
  front_supply_db:
    container_name: front_supply_db
    hostname: front_supply_db
    image: docker.io/library/postgres:16.4-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432